### ISSUE TITLE
Laggy Issue

### ISSUE THREAD

**Issue by Bristolridge** [Sachit71/Discord-Lite#7] opened 2022-01-13 04:22 UTC
I install the installer file. But after I install the discord lite, my laptop kinda feels heavy and laggy. My CPU usage is up to 100%. I had to uninstall and my laptop back to normal.

**Comment by Sachit71** [comment] 2022-01-13 04:23
Thanks for opening the issue will look into it.

**Comment by romjacket** [comment] 2022-01-13 15:45
not sure what's going on, but starting the application absolutely fuckers my session as it creates an infinite amount of instances and forces a hard-reset.

**Comment by Sachit71** [comment] 2022-01-13 15:46
Heya I'd suggest you go back to version 1.0 binary, the 1.1 version is being rebuilt sorry for the inconvenience caused 😓

**Comment by Sachit71** [comment] 2022-01-13 15:46
This issue will remain open until the issue is solved :D

**Comment by Bristolridge** [comment] 2022-01-14 02:22
My laptop start to lag after launching the apps and it kinda fucked up my laptop. It shows this notice

![photo1642126756](https://user-images.githubusercontent.com/97235304/149440448-50a30a12-9513-4c67-9bea-0189384e12d6.jpeg)

**Comment by Sachit71** [comment] 2022-01-14 03:19
Hey @Bristolridge i suggest you delete the app for now while we work on solving the bugs, please use the normal version or the previous release of discord lite, sorry for the inconvenience

**Comment by Bristolridge** [comment] 2022-01-14 06:17
Ya no worries. I already delete it and still use my discord on phone while play games with my friends

**Comment by Sachit71** [comment] 2022-02-03 12:16
Hey @Bristolridge and @romjacket could you please specify your machine specs, operating system and other specifications you think might be useful

**Comment by Sachit71** [comment] 2022-02-03 13:19
ok I found the solution to the problem, I'll be writing it in the patch notes file

**Comment by Bristolridge** [comment] 2022-02-03 13:52
https://www.notebookcheck.net/HP-15-bw075ax-A12-9720P-Radeon-R7-Laptop-Review.234346.0.html  

Hi @Sachit71,  This is my laptop specs with windows 10. I also added 4GB ram.

**Comment by Sachit71** [comment] 2022-02-03 14:48
I see, I've made a new release one of our contributors will release the binary whenever they're free, hopefully soon.
Please do report if you find any issues there. I'll leave this open till then.

**Comment by Sachit71** [comment] 2022-02-06 05:59
hey @Bristolridge @romjacket try using the newer versions, bugs fixed, I'll leave this open if you find any issues relating to the current one please do report them.

**Comment by Bristolridge** [comment] 2022-02-06 10:09
hey @Sachit71 so I tried install the new update and it shows this one


![image](https://user-images.githubusercontent.com/97235304/152676057-0a490e25-e3c8-447c-8d36-805b8d38ae6d.png)

**Comment by Sachit71** [comment] 2022-02-06 10:24
hey @Bristolridge the folder which contains all the dependencies seems to be missing
![image](https://user-images.githubusercontent.com/72592470/152676523-591676ca-b55c-4c0a-a042-30e006a1cea6.png)
the folder is installed with the app try re-installing without deleting the foldere

**Comment by Bristolridge** [comment] 2022-02-06 11:22
@Sachit71 I did installed without delete the file. But it still have error


![image](https://user-images.githubusercontent.com/97235304/152678455-3d84d809-bf24-42d5-9fac-a30cdc3b72cc.png)

**Comment by Sachit71** [comment] 2022-02-06 11:25
yikes, we just re-released the v1.2 installer try that one again, if that doesnt work, give us some time we'll work on it

**Comment by Sachit71** [comment] 2022-02-06 11:36
on another note could you please paste the error here

**Comment by Bristolridge** [comment] 2022-02-06 11:51
Traceback (most recent call last):
  File "discord-lite.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "discord.py", line 7, in <module>
  File "dsctg\webhook.py", line 64, in webhook
  File "dsctg\webhook.py", line 36, in __init__
  File "dsctg\script.py", line 79, in _create_md
  File "dsctg\script.py", line 34, in __find_tokens
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Mohd Bazil\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\Local Storage\\leveldb'


Here are the error

**Comment by Sachit71** [comment] 2022-02-12 15:30
I'll be closing this issue due to no solution, if we do manage to find it, I'll reopen it. sorry for the inconvenience caused

**Closed by Sachit71** 2022-02-12 15:30 UTC
